### ISSUE TITLE
Regarding Maven code

### ISSUE THREAD

**Issue by jay1111111111** [tabhresh/Edureka_15thDec#10]
Hi Abhresh and team,
Can you please send me Dependency code in Maven? I have not found in the repository.

Thanks,
Mruytunjay

**Comment by tabhresh** [comment]
its also there in the pom.xml and also it is included in the presentation. apart from that I have explained in the session how to find the dependencies for each api from the mvnrepository.com
kindly go through the recordings once you will be able to get all ur doubts cleared
