### ISSUE TITLE
screenshots with HTML unit browser

### ISSUE THREAD

**Issue by Maheshwaridec15** [tabhresh/Edureka_15thDec#11]
Hi, 
can you please explain how to take screen shots with phantomjs and htmlunit browser?

**Comment by tabhresh** [comment]
when there is not visual representation how will you be able to get a screenshot.. you need to think logically...

**Comment by Maheshwaridec15** [comment]
[535_m12_CaseStudy_v3.1.pdf](https://github.com/tabhresh/Edureka_15thDec/files/2794910/535_m12_CaseStudy_v3.1.pdf)


It is from the module assignments from edureka team only, which asks for such use cases to be performed.
And so arises the doubt?????.
There are standard "view solution" also which is already given, out dated  or dunno, which i s not working when i tried to implement.
If experts are designing such case studies, why dint they think so?

**Comment by tabhresh** [comment]
I am waiting for the Content Team for a response lets see what they have to say!

**Comment by tabhresh** [comment]
pls contact support team for the same
