### ISSUE TITLE
output is different in htmlunit browser

### ISSUE THREAD

**Issue by Maheshwaridec15** [tabhresh/Edureka_15thDec#12]
package module12;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;

public class Htmlunit {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		 
        WebDriver driver = new HtmlUnitDriver();
         	
        driver.get("http://www.google.com");					

		 	
        WebElement element = driver.findElement(By.name("q"));	
        
       	
       element.sendKeys("Edureka");	
      
       	
       element.submit();			
       
		
       System.out.println("Page title is: " + driver.getTitle());		
       
       driver.quit();		

	}

**Comment by Maheshwaridec15** [comment]
In html unit driver,i get the output as : "google"
instead of "edureka"

but the outpis fine when i use "phanthomjs driver"

**Comment by Maheshwaridec15** [comment]
Yes even after adding Thread.sleep(5000);
its still the same.
Page title is: edureka - Google Search (in phanthomjs)
Page title is: Google (in HTMLUnit browser)

**Comment by tabhresh** [comment]
Pls raise the support tickets on Edureka site for the doubts! You have a dedicated team for your support. Kindly get in touch with them with all your queries
