### ISSUE TITLE
Data Driven Test Issue 

### ISSUE THREAD

**Issue by nthapa3413** [tabhresh/Edureka_15thDec#14]
I tried copy paste the excel file that has my test data in my Project , when i click on that file its shows this ...i have added all the apache poi jar files on the project. What should i do?
PKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPKPK

**Comment by tabhresh** [comment]
I am unable to understand your concern due to the view that I got has all the symbols check attachment

![nthapa issues](https://user-images.githubusercontent.com/22336822/51727929-3f413f00-2094-11e9-9e99-6579327ac33e.JPG)


Didnt get clear idea on what is your issue and what steps you have implemented.

**Comment by tabhresh** [comment]
are you trying to see the excel in eclipse and is it .xls   , if yes then the problem is regarding the format of excel which is not supported. 
Other thing to check is format of excel file
for POI use .xlsx and for JXL use .xls file
Take the screenshot and share it

**Comment by nthapa3413** [comment]
yes i want to open excel from eclipse and i have saved excel file in .xlsx
format.
I have attached the screenshot .


*Regards,*
*Nistha Thapa*

**Comment by tabhresh** [comment]
Its ok if its not opening in eclipse.. is it working fine when you open it in windows and any special characters implemented in the sheet?

Try recreating the file. I think it seems to be file compatibility related issue nothing to worry change the file.

**Comment by nthapa3413** [comment]
oh okay .. yes it is opening fine outside eclipse . Thank you .

*Regards,*
*Nistha Thapa*
