### ISSUE TITLE
Script not fetching data form excel

### ISSUE THREAD

**Issue by pradeepst13** [tabhresh/Edureka_15thDec#15]
package module9;

import java.io.FileInputStream;
import java.io.IOException;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

public class Module9assingment {
	
	WebDriver driver;
	Workbook wb;
	Sheet sh;
	int rownum ;
	int colnum;
	
	@Test
	
	public void OpenAPP() throws InterruptedException, BiffException, IOException {
		
		System.setProperty("webdriver.chrome.driver", "C:\\ChromeDriver\\chromedriver.exe");
		    driver= new ChromeDriver();
	
		    
		    
		   driver.get("https://www.edureka.co/");
		   driver.findElement(By.linkText("Log In")).click();
			Thread.sleep(1000);
			
			String filepath= "C:\\Users\\pthippeswamy\\Documents\\ONE Drive\\Selenium\\SeleniumClass\\src\\module9\\TESTDATA1.xls";
			 FileInputStream file = new FileInputStream(filepath);
			 
			 Workbook workbook = Workbook.getWorkbook(file);
			 Sheet sheet= workbook.getSheet(0);
			 
			 int rowCount = sheet.getRows();
			 
			 for (int i=0; i<rowCount; i++) {

				 String Email= sheet.getCell(0,i).getContents();
				 String Password= sheet.getCell(0, i).getContents();
				
				 driver.findElement(By.xpath("//input[@id='si_popup_email']")).sendKeys();
				 Thread.sleep(1000); 
				
				 driver.findElement(By.xpath("//input[@id='si_popup_passwd']")).sendKeys();
				 Thread.sleep(1000); 
				 driver.findElement(By.xpath("//button[@class='clik_btn_log btn-block pagesense_en_track']")).click();
				 
				 Thread.sleep(1000); 
				 
				 
				 
			 }
			
			
	}
	
	
}

**Comment by tabhresh** [comment]
I could not run the code as I don't have the supporting files and apart from that I don't see the usage of Data provider annotations and the scripting is not done similar to what we have discussed during the sessions.
