### ISSUE TITLE
sharing pom.xml between two Maven projects.

### ISSUE THREAD

**Issue by Maheshwaridec15** [tabhresh/Edureka_15thDec#17]
how to share the 'line of codes' or methods from one maven project to another maven project?
I wanted to reuse the codes of first maven project in my second maven project means.
How to do this?
Are there specific maven dependencies or plugins available to solve this purpose?
If so,How should I add this in my pom.xml?
Can you pls help me.

**Comment by tabhresh** [comment]
Not possible!

Pls raise the questions with support team as they done have any tickets raised by you yet. Pls use that medium to get the support.
