### ISSUE TITLE
Module 11 assignment 

### ISSUE THREAD

**Issue by pradeepst13** [tabhresh/Edureka_15thDec#18]
[Module11assignment.zip](https://github.com/tabhresh/Edureka_15thDec/files/2825001/Module11assignment.zip)

i have attached the Module 11 assignment if uploading photo to edureka portal.The scripts executes successfull but does not upload any the Photo. Could you please guide me .

**Comment by tabhresh** [comment]
let me check

**Comment by tabhresh** [comment]
its working at my end!
