### ISSUE TITLE
About Keyword driven testing and Hybrid testing framework

### ISSUE THREAD

**Issue by nthapa3413** [tabhresh/Edureka_15thDec#19]
Hi abhresh,
I copied the excel driver class file to the utility package to practice keyword-driven framework and hybrid framework. but after importing all the requirement from apache poi, it still gives me an error on this line 

if(oCell.getCellType() == Cell.CELL_TYPE_NUMERIC){

error: 
.CELL_TYPE_NUMERIC cannot be resolved or is not a field. 
Please let me know what do I need to do. Thank you.

**Comment by tabhresh** [comment]
pls raise ticket with the support team about ur issue along with code and we will support u..
