### ISSUE TITLE
Xpath attribute and xpath function

### ISSUE THREAD

**Issue by deba17** [tabhresh/Edureka_15thDec#2]
Hi , 

While finding a locator can we use a conditional check with a xpath attribute and xpath function , example we have a input type is email and name is email , lets say we will find the element by type = 'email' and name start_with 'ema' .

**Comment by tabhresh** [comment]
Hi, Clubbing two functions are possible but not correct as per the coding standards. If things works fine with one functions why there is a need to make things complicated and use two functions.
So my suggestion would be use only one function at a time and use best suited one to get right unique customized XPath for that element.
