### ISSUE TITLE
element not interactable or element not foun

### ISSUE THREAD

**Issue by pradeepst13** [tabhresh/Edureka_15thDec#4]
I am getting this error message even though the  xpath is unique

package openbrowser;

import org.openqa.selenium.By;

import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;

public class Module4assignment {

	public static void main(String[] args) {
		
		//Launch ChromeBrowser 
		
		System.setProperty("webdriver.chrome.driver", "C:\\ChromeDriver\\chromedriver.exe");
		WebDriver driver= new ChromeDriver();
					
		driver.get("https://www.goindigo.in/?linkNav=home_header");
		
		driver.findElement(By.id("oneWayTrip")).click();
		
		driver.findElement(By.name("or-src")).click();
				
			
	driver.findElement(By.xpath("//*[@id='mcSrcModal-1']/div/div/div[2]/div/div/div/input and @")).sendKeys("bangalore");

**Comment by tabhresh** [comment]
You can try using wait commands / synchronization commands. Its all about managing the flow of execution and time required for that element to be accessible.

**Comment by tabhresh** [comment]
Have a look at the response to other issue raised by other member

https://github.com/tabhresh/Edureka_15thDec/issues/5
