### ISSUE TITLE
What is "listeners " in TestNG? This concept  is required in one of our case studies.

### ISSUE THREAD

**Issue by Maheshwaridec15** [tabhresh/Edureka_15thDec#6]

**Comment by tabhresh** [comment]
Hi,
As per my knowledge this concept is not a part of the course and i dont see it anywhere in the slides neither in the case study of module 6. Can you tell me where it mentioned?

**Comment by Maheshwaridec15** [comment]
I saw it in the case study - module 7

**Comment by tabhresh** [comment]
Pls ignore that, as it is not a part of the latest content that we are going through, but if you still want to learn you can explore the same and then practice and implement it into the case study.

**Comment by tabhresh** [comment]
https://testng.org/doc/documentation-main.html#testng-listeners
Go ahead with this URL it may help!

There are many additional topics too, which you should explore to make your self independent of being able to learn your self. 

Best Luck!
