### ISSUE TITLE
How can i rerun the failed test cases alone using selenium.. i mean i want to filter the failed test cases alone from the test suite and re-run.

### ISSUE THREAD

**Issue by Maheshwaridec15** [tabhresh/Edureka_15thDec#9]

**Comment by tabhresh** [comment]
Kindly enter the questions in the body sections(matter writing section) of the issue instead on typing into the headings itself. I cant get you question completely visible.

**Comment by Maheshwaridec15** [comment]
How can i rerun the failed test cases alone using selenium.. i mean i want to filter the failed test cases alone from the test suite and re-run.

**Comment by Maheshwaridec15** [comment]
any updates on this issue?
